name: CI

on:
  - pull_request
  - push

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - codestyle
          - docstyle

    steps:
      - uses: actions/checkout@master

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install tox
        run: python -m pip install tox

      - name: Run lint
        run: tox -e ${{ matrix.target }}

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python:
          - 2.7
          - 3.4
          - 3.5
          - 3.6
          - 3.7
          - 3.8
          - 3.9
          - pypy2
          - pypy3

    steps:
      - uses: actions/checkout@master

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install tox
        run: python -m pip install tox

      - name: Run tests
        run: tox -e py
